// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oohqztzgaermznwtmmrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vaHF6dHpnYWVybXpud3RtbXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTM3NTksImV4cCI6MjA2MzkyOTc1OX0.otBx5P4G0OLV-0Kw2OoREYZGt_LKy8mLPqYqYFHlgF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);